apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: db2-source
  namespace: data-dev
  labels:
    strimzi.io/cluster: my-connect
spec:
  class: io.debezium.connector.db2.Db2Connector
  tasksMax: 1
  config:
    # DB Connection via proxy
    database.hostname: "db2-proxy"     
    database.port: 60004
    database.user: "<Username>"
    database.password: "<Password>"   
    database.dbname: "<DBName>"
    database.server.name: "<DBServerName>"  

    topic.prefix: "db2"
    table.include.list: "<schema.table_name>"

    snapshot.mode: "initial"           
    heartbeat.interval.ms: 5000         
    schema.history.internal.kafka.bootstrap.servers: "<kafka-url:port>"
    schema.history.internal.kafka.topic: "db2.schema_history"

    key.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true

    transforms: unwrap
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: true
    # transforms.unwrap.delete.handling.mode: rewrite    
