apiVersion: v1
kind: Service
metadata:
  name: db2-proxy
  namespace: data-dev
spec:
  type: ClusterIP
  selector:
    app: db2-proxy
  ports:
    - name: db2
      port: 60004
      targetPort: 60004
