apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-plugin-pvc
  namespace: data-dev
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
