apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-0-my-cluster-dual-role-0
  namespace: data-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard    
  resources:
    requests:
      storage: 10Gi
