FROM maven:3.9.2-eclipse-temurin-17 AS builder

WORKDIR /app
COPY lowercase-transform /app/lowercase-transform
WORKDIR /app/lowercase-transform

# Skip compiling and running tests
RUN mvn clean package -Dmaven.test.skip=true
